<a href="https://colab.research.google.com/github/Claudio-Ferriz/Proyecto-AP-PS/blob/main/Proyecto_AP_PS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías

In [1]:
# Importación y ejecución de las librerías de Python para el análisis y modelado
# de datos.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dataframes

In [2]:
# Generación del primer dataframe referido a Aprobación Presidencial el cual
# se encuentra en formato excel importando desde el repositorio
# github del proyecto.


df_ap = pd.read_excel('https://github.com/Claudio-Ferriz/Proyecto-AP-PS/raw/refs/heads/main/Copia%20de%20Encuestas%20Aprobaci%C3%B3n%20Presidencial%202025%20-%20Solo%20Base%20Integrada.xlsx')

In [3]:
# Generación del segundo dataframe referido a Protesta Social el cual
# se encuentra en formato excel importando desde el repositorio
# github del proyecto.


df_ps = pd.read_excel('https://github.com/Claudio-Ferriz/Proyecto-AP-PS/raw/refs/heads/main/Copia%20de%20protesta_social_aggregated_data_up_to-2026-02-28.xlsx')

# Exploratory Data Analysis (EDA)

## Dataframe Aprobación Presidencial

In [4]:
df_ap

,País,Región I,Región II,Tipo de Encuesta,Consultora,Mes,Año,Fecha,Aprueba,Presidente,...,Población,Indice Desarrollo Humano,PBI per capita (PPA),Tasa Desempleo,Inflación,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Alemania,Europa,Europa,Online,Televisión pública ARD,Abril,2020.0,2020-04-03,64.0,Angela Merkel,...,83160343.0,0.944,57905,5.9,0.4,NaN,NaN,NaN,NaN,NaN
1,Alemania,Europa,Europa,Online,Civey,Mayo,2020.0,2020-05-06,61.0,Angela Merkel,...,83160343.0,0.944,57905,5.9,0.5,https://app.civey.com/dashboards/live-lageberi...,NaN,NaN,NaN,NaN
2,Alemania,Europa,Europa,Online,Civey,Mayo,2020.0,2020-05-21,64.0,Angela Merkel,...,83160343.0,0.944,57905,5.9,0.5,https://civey.com/pro/loesungen/corona-lageber...,NaN,NaN,NaN,NaN
3,Alemania,Europa,Europa,Online,Infratest Dimap,Mayo,2020.0,2020-05-31,68.0,Angela Merkel,...,83160343.0,0.944,57905,5.9,0.5,NaN,NaN,NaN,NaN,NaN
4,Alemania,Europa,Europa,Online,Infratest Dimap,Junio,2020.0,2020-06-16,40.0,Angela Merkel,...,83160343.0,0.944,57905,5.9,-0.3,https://www.americaeconomia.com/politica-socie...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2864,Colombia,América,América Latina,Presencial,CB consultora,Noviembre,2025.0,2025-11-20,36.7,Gustavo Petro,...,NaN,NaN,NaN,NaN,NaN,https://cbconsultoraop.com/noviembre-2025-rank...,NaN,NaN,NaN,NaN
2865,Colombia,América,América Latina,Presencial,CB consultora,Octubre,2025.0,2025-10-22,38.1,Gustavo Petro,...,NaN,NaN,NaN,NaN,NaN,https://cbconsultoraop.com/octubre-2025-rankin...,NaN,NaN,NaN,NaN
2866,Paraguay,América,América Latina,Presencial,CB consultora,Noviembre,2025.0,2025-11-22,41.3,Santiago Peña,...,NaN,NaN,NaN,NaN,NaN,https://cbconsultoraop.com/octubre-2025-rankin...,NaN,NaN,NaN,NaN
2867,Perú,América,América Latina,Telefónica,CB consultora,Noviembre,2025.0,2025-11-24,32.5,José Jerí,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,Perú,América,América Latina,Telefónica,CB consultora,Octubre,2025.0,2025-10-22,29.5,José Jerí,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dataframe Protesta Social

In [5]:
df_ps

,Mes,Año,País,Tipo de Protesta,Cantidad de Eventos de Protesta
0,Septiembre,2020,Argentina,Battles,1
1,Mayo,2021,Argentina,Explosions/Remote violence,1
2,Julio,2018,Argentina,Explosions/Remote violence,2
3,Julio,2018,Argentina,Explosions/Remote violence,1
4,Noviembre,2018,Argentina,Explosions/Remote violence,1
...,...,...,...,...,...
170339,Noviembre,2021,Inglaterra,Riots,1
170340,Abril,2022,Inglaterra,Riots,1
170341,Diciembre,2022,Inglaterra,Riots,1
170342,Mayo,2023,Inglaterra,Riots,1
170343,Junio,2024,Inglaterra,Riots,1